---
title: "PA1_template"
output: html_document
date: "`r Sys.Date()`"
---
```{r}
library(datasets)
library(knitr)
library(markdown)
library(timeDate)

### Loading And Reading The Data
link<-"https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
fn<-"repdata_data_activity.zip"
download.file(link,fn)
unzip(fn)
a<-read.csv("activity.csv")
head(a,3)

### Calculating The Total Number Of Steps Taken Each Day And The Average Number Of Steps Taken Of The 5-minute Interval
StepPerDay<-aggregate(steps~date, a, sum)
AveragePerStep<-aggregate(steps~interval, a, mean)
head(StepPerDay,3)
head(AveragePerStep,3)

### Making A Histogram And Calculating The Mean And Median Total Number Of Steps Taken Per Day
hist(StepPerDay$steps, col="grey", xlab="Step", main="Total Number of Steps Per Day")
MeanMedian<-c(mean(StepPerDay$steps),median(StepPerDay$steps))
names(MeanMedian)<-c("Mean","Median")
MeanMedian

### Make A Time Series Plot Of The 5-minute Interval
with(data=AveragePerStep, plot(x=AveragePerStep$interval,y=AveragePerStep$steps, type="l", col="brown"))
title(main="Average number of steps taken in 5-min interval")
max(AveragePerStep$steps)

### Making A Subset
SubData<-subset(AveragePerStep,steps==max(AveragePerStep$steps))
head(SubData,3)
SubData$interval

### Creating A New Column "Newsteps"
a$Newsteps<-AveragePerStep$steps
a$Newsteps[is.na(a$Newsteps)]<-a$Newsteps
a$Newsteps<-NULL
head(a$Newsteps,3)
NewData<-a
head(NewData,3)

### Using The New Data Subset To Calculate The Total Number Of Steps Per Day
SumData<-aggregate(steps~date, NewData, sum)
head(SumData,3)
hist(SumData$steps, col="green", xlab="Step", main="Total Number of Steps Per Day")
MeanMedian2<-c(mean(SumData$steps),median(SumData$steps))
names(MeanMedian2)<-c("Mean","Median")
MeanMedian2

### Using The isWeekday() Function To Check
NewData$Weekday<-isWeekday(NewData$date)
head(NewData,3)

### Subset And Calculate The Average Steps For Weekday And Weekend
WeekDay<-subset(NewData, NewData$Weekday=="TRUE")
WeekDayMean<-aggregate(steps~interval, WeekDay, mean)
head(WeekDayMean,3)
Weekend<-subset(NewData, NewData$Weekday=="FALSE")
WeekendMean<-aggregate(steps~interval, Weekend, mean)
head(Weekend,3)

### Make The Panel Plot
layout(matrix(c(1,1,2,2), 2, 2, byrow = TRUE))
plot(x=WeekDayMean$interval, y=WeekDayMean$steps, xlab="Interval", ylab="Number Of Steps", main="Weekday", type="l", col="orange")
plot(x=WeekendMean$interval, y=WeekendMean$steps, xlab="Interval", ylab="Number Of Steps", main="Weekend", type="l", col="blue")